# This code is proprietary to AquaTrak. Unauthorized use is strictly prohibited.

# =============================================================================
# KUBERNETES PERSISTENT VOLUMES FOR AQUATRAK STORAGE
# =============================================================================

---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquatrak-postgres-pvc
  namespace: aquatrak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# Redis PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquatrak-redis-pvc
  namespace: aquatrak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
# Uploads PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquatrak-uploads-pvc
  namespace: aquatrak
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

---
# Logs PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquatrak-logs-pvc
  namespace: aquatrak
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# Prometheus PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquatrak-prometheus-pvc
  namespace: aquatrak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# Grafana PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquatrak-grafana-pvc
  namespace: aquatrak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 