# This code is proprietary to AquaTrak. Unauthorized use is strictly prohibited.

# =============================================================================
# KUBERNETES SECRET FOR AQUATRAK SENSITIVE DATA
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: aquatrak-secrets
  namespace: aquatrak
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  SECRET_KEY: <base64-encoded-secret-key>
  POSTGRES_PASSWORD: <base64-encoded-postgres-password>
  DATABASE_URL: <base64-encoded-database-url>
  REDIS_URL: <base64-encoded-redis-url>
  
  # SSL Certificates (if using custom certificates)
  ssl-cert.pem: <base64-encoded-ssl-cert>
  ssl-key.pem: <base64-encoded-ssl-key>
  
  # API Keys (if needed)
  SATELLITE_API_KEY: <base64-encoded-satellite-api-key>
  WEATHER_API_KEY: <base64-encoded-weather-api-key> 